### ISSUE TITLE
Will not build on Android Studio

### ISSUE THREAD

**Issue by BillMac4440** [weplenish/flutter_wifi_connect#7]
3 errors in flutter_wifi_connect\FlutterWifiConnectPlugin.kt: (317,5), (341,49), and (350.51): Smart cast to 'ConnectivityManager.NetworkCallback' is impossible because 'this.networkCallback' is a mutable property that could have been changed by this time.

**Comment by vipero07** [comment]
This sounds new to me, could be a new build issue with android studio though to be honest I've only ever built it in Visual Studio Code. Will look into it further.

**Comment by BillMac4440** [comment]
Thanks, I tried wifi_iot.  That built and connected, but does not make a route on the connected network.
Trying to find a solution to run on Android 10.  wifi_configuration is not updated for Android 10, but worked fine 6-8.

**Comment by vipero07** [comment]
Internally I've been using this for v-next of our application, it seems to work well for me on Android 10 and older versions, but again, I haven't been trying to build in android studio, so its definitely something I've got to look into. The fix for that particular issue shouldn't be much more than adding a !! or ? to test or coerce the nullable.

**Comment by BillMac4440** [comment]
I had tried the !! and something blew up.  Don't remember because I moved on to something else.  That is when I found the wifi_iot won't make a route.  I could attach to the AP, verify a network address on the subnet, but could not hit the REST service on the module.  Still trying to get something to work for Android 10.  My IoT configure app works up to Android 9.

**Comment by MohammedZ666** [comment]
I got the same issues in visual studio code,  My flutter doctor:
![image](https://user-images.githubusercontent.com/50874919/107110535-d0963f00-6872-11eb-87b8-740db2e6d1b6.png)

My errors: 
`Launching lib\main.dart on SM J700H in debug mode...
lib\main.dart:1
e: D:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_wifi_connect-0.0.7\android\src\main\kotlin\com\weplenish\flutter_wifi_connect\FlutterWifiConnectPlugin.kt: (317, 53): Smart cast to 'ConnectivityManager.NetworkCallback' is impossible, because 'this.networkCallback' is a mutable property that could have been changed by this time
e: D:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_wifi_connect-0.0.7\android\src\main\kotlin\com\weplenish\flutter_wifi_connect\FlutterWifiConnectPlugin.kt: (341, 49): Smart cast to '<no name provided>' is impossible, because 'networkCallback' is a mutable property that could have been changed by this time
e: D:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_wifi_connect-0.0.7\android\src\main\kotlin\com\weplenish\flutter_wifi_connect\FlutterWifiConnectPlugin.kt: (350, 51): Smart cast to 'ConnectivityManager.NetworkCallback' is impossible, because 'this.networkCallback' is a mutable property that could have been changed by this time

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_wifi_connect:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

I am building this on **visual studio code**, please address this issue

**Comment by hhy** [comment]
the build fails in both vscode and flutter command build
![image](https://user-images.githubusercontent.com/1216971/108438530-6c359100-721d-11eb-9fb1-75cffafc2374.png)


e: /home/tom/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wifi_connect-0.0.7/android/src/main/kotlin/com/weplenish/flutter_wifi_connect/FlutterWifiConnectPlugin.kt: (317, 53): Smart cast to 'ConnectivityManager.NetworkCallback' is impossible, because 'this.networkCallback' is a mutable property that could have been changed by this time
e: /home/tom/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wifi_connect-0.0.7/android/src/main/kotlin/com/weplenish/flutter_wifi_connect/FlutterWifiConnectPlugin.kt: (341, 49): Smart cast to '<no name provided>' is impossible, because 'networkCallback' is a mutable property that could have been changed by this time
e: /home/tom/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wifi_connect-0.0.7/android/src/main/kotlin/com/weplenish/flutter_wifi_connect/FlutterWifiConnectPlugin.kt: (350, 51): Smart cast to 'ConnectivityManager.NetworkCallback' is impossible, because 'this.networkCallback' is a mutable property that could have been changed by this time

**Comment by techno-disaster** [comment]
@vipero07 any updates on this? Also could you send the flutter doctor for which this works correctly?

**Comment by techno-disaster** [comment]
@BillMac4440 were you able to find a workaround or a diffrent lib? I need to connect to a open wifi

**Comment by BillMac4440** [comment]
I used https://github.com/alternadom/WiFiFlutter, I had to use a branch with the "withInternet" to be able to set it to false.  There is work on hidden which is what I need, but the fork was 12 commits back from the branch I used and 2 ahead of the main, so it all needs to get merged.  It did work where I set the IoT device to show its SSID.    I went through a bunch of libs to find something that would work.  I work on embedded stuff.  I use this Flutter app to check the embedded side, but make no claims on being up to speed enough to help with these libs!  If you check on the other one and look at my discussion, it has how to setup the route.

**Comment by techno-disaster** [comment]
> I used https://github.com/alternadom/WiFiFlutter, I had to use a branch with the "withInternet" to be able to set it to false. There is work on hidden which is what I need, but the fork was 12 commits back from the branch I used and 2 ahead of the main, so it all needs to get merged. It did work where I set the IoT device to show its SSID. I went through a bunch of libs to find something that would work. I work on embedded stuff. I use this Flutter app to check the embedded side, but make no claims on being up to speed enough to help with these libs! If you check on the other one and look at my discussion, it has how to setup the route.

Tried using that but for some reason I keep getting unknown ssid even tho i wait for connecting to the wifi. Is your code open source? Or if possible could you share a small piece of it? (the ssid and connecting)

**Comment by BillMac4440** [comment]
// This handles connection to an access point
  // Note 01/25/2020:  The library does not handle hidden SSID's.
  Future<void> connectSoftAP() async {
    connectDone = false;
    errorString = "";
    print("In connect, SoftAp = ${softAP.getSSID()}");
    print("In connect, Key = ${softAP.getKey()}");
    WiFiForIoTPlugin();

    await WiFiForIoTPlugin.connect(softAP.getSSID(),
            password: softAP.getKey(),
            security: NetworkSecurity.WPA,
            withInternet: false,
            joinOnce: true)
        .then((value) => {lastConnectStatus = value})
        .catchError((e) {
      lastConnectStatus = false;
      errorString = e.toString();
      print("Error is: $e");
    });
    if (lastConnectStatus)
      print("Network connected");
    else
      print("Network not connected");
    connectDone = true;
  }
The above works for me

**Comment by vipero07** [comment]
The above merge should fix the issue, it was related to a nullable potentially not being null at the time it is being accessed.

**Comment by rdmo94** [comment]
The issue still persists in my project running flutter 2.5.3. Anyone else still experiencing this issue? Is this package considered deprecated?
